### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by weaming** [reorx/drawtable#1]
* https://github.com/reorx/drawtable/blob/master/drawtable/__init__.py#L88 应该先转化成str
* 中文宽度计算不正确

**Comment by reorx** [comment]
1. row 里面的元素好像只会是 str，不用转换？
2. 太麻烦了，pr welcome

**Comment by weaming** [comment]
1. 我就传了个 int，然后只能自己手动 str 了

**Comment by reorx** [comment]
这是 by design 的， draw() 不能预计传进来的数组每个元素是什么类型、要怎么处理，所以应该先保证数据合乎其需求，然后再传入。
